### PR TITLE
Added OSCKit to implementations 

### PR DESCRIPTION
**Pull request by sammysmallman**

### CODE REVIEW

**Comment by matthewjameswright** [comment]
Hi, Sammy - thank you for this contribution!

It appears that the name "OSCKit" has no connection to my long-deprecated 1998 "OSC Kit" (http://opensoundcontrol.org/publications/1998-Implementation-and-Performance-Issues-with-OpenSound-Control.html)

Could I ask you to clarify that point?

Also, the site's implementations/*.md files are auto-generated by the script build-implementations.sh, from the source file http://opensoundcontrol.org/implementations.tsv 

It would be nice if the source was in YAML or something nicer to edit than TSV, with bidirectional translation to MD, so that developers could code new pages in MD as you've done.  But that's not how the site currently works; the repo contains implementations/*.md files only so that "git status" will show what changed after editing the big TSV file and re-running build-implementations

**Comment by sammysmallman** [comment]
Hey Matt,

Yes that is correct there is no connection to the OSC Kit from 1998. The name is purely like that to keep within the naming style Apple give to most of their libraries and this package is aimed towards Apple platforms.

I have committed a fix hopefully adding OSCKit into the right file with the correct formatting. Let me know if you need me to do anything else.

Thanks!

**Comment by matthewjameswright** [comment]
Thanks again for this; sorry for the delay in accepting your revised pull request.  Your new page now appears on the site: http://opensoundcontrol.stanford.edu/implementations/OSCKit.html

**Comment by sammysmallman** [comment]
My pleasure. I'll have a few more coming in the next month or so:
- CoreOSC which is aimed to be pure infrastructural OSC code, transport agnostic and a base for things like OSCKit (https://github.com/sammysmallman/CoreOSC)
- OSCSmith an OSC testing tool for macOS.
CleanShot 2021-08-13 at 19 34 39@2x

**Pull request merged**
