### PR TITLE
Update cl-osc.md

### PR DESCRIPTION
**Pull request by zzkt**

### CODE REVIEW

**Comment by matthewjameswright** [comment]
Thank you for these URL updates!

I ask you to please change the URLs in the file implementations.tsv, from which cl-osc.md is automatically generated.

(I just added a new paragraph about this to the bottom of https://opensoundcontrol.stanford.edu/contribute.html)

best
-Matt

**Comment by zzkt** [comment]
`implementations.tsv` is also updated now

**Comment by matthewjameswright** [comment]
Thanks!  May I also add nik gaffney / https://github.com/zzkt to http://opensoundcontrol.org/contributors.html ?

**Comment by matthewjameswright** [comment]
Also it seems that the status should change from "Legacy" to "Active" (per https://opensoundcontrol.stanford.edu/implementation-status.html)

**Comment by zzkt** [comment]
sure. thanks!

**Comment by zzkt** [comment]
...and the status oscillates between "Legacy" and "Active"

**Comment by matthewjameswright** [comment]
OK, the updates are now published.  Thanks again!!!

**Pull request merged**
